/**
 * The MIT License (MIT)
Copyright (c) 2015 Saqib Nizam Shamsi
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
 */

public class Files {
	
	private static String NAME_OF_THE_FILE_CONTAINING_NAMES_OF_BRANCH_EVENTS = "branchevents.txt";
	private static String NAME_OF_THE_FILE_CONTAINING_NAMES_OF_CENTRAL_EVENTS = "centralevents.txt";
	private static String NAME_OF_THE_FILE_CONTAINING_COLLEGE_ID_RANGE = "college_ids.txt";
	private static String NAME_OF_THE_FILE_CONTAINING_EXTERNAL_ID_RANGE = "external_ids.txt";
	private static String NAME_OF_THE_FILE_CONTAINING_PASSWORD = "password";
	
	public static String getNAME_OF_THE_FILE_CONTAINING_PASSWORD() {
		return NAME_OF_THE_FILE_CONTAINING_PASSWORD;
	}
	public static void setNAME_OF_THE_FILE_CONTAINING_PASSWORD(
			String nAME_OF_THE_FILE_CONTAINING_PASSWORD) {
		NAME_OF_THE_FILE_CONTAINING_PASSWORD = nAME_OF_THE_FILE_CONTAINING_PASSWORD;
	}
	public static String getNAME_OF_THE_FILE_CONTAINING_NAMES_OF_BRANCH_EVENTS() {
		return NAME_OF_THE_FILE_CONTAINING_NAMES_OF_BRANCH_EVENTS;
	}
	public static void setNAME_OF_THE_FILE_CONTAINING_NAMES_OF_BRANCH_EVENTS(
			String nAME_OF_THE_FILE_CONTAINING_NAMES_OF_BRANCH_EVENTS) {
		NAME_OF_THE_FILE_CONTAINING_NAMES_OF_BRANCH_EVENTS = nAME_OF_THE_FILE_CONTAINING_NAMES_OF_BRANCH_EVENTS;
	}
	public static String getNAME_OF_THE_FILE_CONTAINING_NAMES_OF_CENTRAL_EVENTS() {
		return NAME_OF_THE_FILE_CONTAINING_NAMES_OF_CENTRAL_EVENTS;
	}
	public static void setNAME_OF_THE_FILE_CONTAINING_NAMES_OF_CENTRAL_EVENTS(
			String nAME_OF_THE_FILE_CONTAINING_NAMES_OF_CENTRAL_EVENTS) {
		NAME_OF_THE_FILE_CONTAINING_NAMES_OF_CENTRAL_EVENTS = nAME_OF_THE_FILE_CONTAINING_NAMES_OF_CENTRAL_EVENTS;
	}
	public static String getNAME_OF_THE_FILE_CONTAINING_COLLEGE_ID_RANGE() {
		return NAME_OF_THE_FILE_CONTAINING_COLLEGE_ID_RANGE;
	}
	public static void setNAME_OF_THE_FILE_CONTAINING_COLLEGE_ID_RANGE(
			String nAME_OF_THE_FILE_CONTAINING_COLLEGE_ID_RANGE) {
		NAME_OF_THE_FILE_CONTAINING_COLLEGE_ID_RANGE = nAME_OF_THE_FILE_CONTAINING_COLLEGE_ID_RANGE;
	}
	public static String getNAME_OF_THE_FILE_CONTAINING_EXTERNAL_ID_RANGE() {
		return NAME_OF_THE_FILE_CONTAINING_EXTERNAL_ID_RANGE;
	}
	public static void setNAME_OF_THE_FILE_CONTAINING_EXTERNAL_ID_RANGE(
			String nAME_OF_THE_FILE_CONTAINING_EXTERNAL_ID_RANGE) {
		NAME_OF_THE_FILE_CONTAINING_EXTERNAL_ID_RANGE = nAME_OF_THE_FILE_CONTAINING_EXTERNAL_ID_RANGE;
	}
	

}
